Build: CI: Improve: Automate inferring org/repo so user can ignore
- When run locally, bin/update-poetry required user to set environ
  to specify org/repo. But now the script uses `tomlq` to read the
  url from pyproject.toml.

- When run from GHA, it's easy enough to pass ${{ github.repository }},
  but now workflows can omit the environ, and this script will read
  the 'origin' remote (because on GHA you know what remote that is,
  unlike when run from an arbitrary user environment).

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -5,13 +5,6 @@
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-# FIXME/2023-11-04 04:43: Customize this for each project.
-# - Should workflow pass it in?
-# - What about running locally?
-# USAGE: From GHA, e.g.,
-#   REPO_ORG_PROJ="${{ github.repository }}" ./.github/bin/update-poetry
-REPO_ORG_PROJ="${REPO_ORG_PROJ:-doblabs/easy-as-pypi}"
-
 # FIXME/2023-11-03: Make the strings in functions below user-configurable,
 # including: Branch name, Commit message, PR name/title.
 UPDEPS_LABEL_NAME="poetry.lock"
@@ -20,15 +13,21 @@ UPDEPS_LABEL_NAME="poetry.lock"
 UPDEPS_USER_EMAIL="landonb@users.noreply.github.com"
 UPDEPS_USER_NAME="update-poetry"
 
+# The UPDEPS_REPO_ORG_PROJ environ will be inferred at runtime.
+# - You can also set from workflow, e.g.,
+#     UPDEPS_REPO_ORG_PROJ="${{ github.repository }}" ./.github/bin/update-poetry
+#
+#  UPDEPS_REPO_ORG_PROJ=
+
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 source_deps () {
-  insist_cmd 'git'
-  insist_cmd 'poetry'
-  insist_cmd 'gh'
+  _updeps_insist_cmd 'git'
+  _updeps_insist_cmd 'poetry'
+  _updeps_insist_cmd 'gh'
 
   # Ensure coreutils installed (from Linux pkg. mgr., or from macOS Homebrew).
-  insist_cmd 'realpath'
+  _updeps_insist_cmd 'realpath'
 
   # For `print_canon_scoped_head` (which uses `identify_scope_ends_at` from git-put-wise).
   # - Supports running this script on local Dev repo with PRIVATE commits.
@@ -44,7 +43,7 @@ source_deps () {
   # . "$(dirname "$(realpath "$0")")/../../deps/sh-git-nubs/bin/git-nubs.sh"
 }
 
-insist_cmd () {
+_updeps_insist_cmd () {
   local cmdname="$1"
 
   command -v "${cmdname}" > /dev/null && return 0 || true
@@ -65,6 +64,12 @@ print_prog () {
 update_poetry_update () {
   assert_git_status_tidy
 
+  local branch_name
+  branch_name="$(print_branch_name)"
+
+  local remote_name
+  remote_name="$(git_upstream_remote)"
+
   poetry_update_lock
 
   assert_git_status_0_or_1_changes
@@ -72,17 +77,11 @@ update_poetry_update () {
   assert_git_status_only_poetry_lock_changed_if_any
 
   if test -n "$(git status --porcelain=v1)"; then
-    local branch_name
-    branch_name="$(print_branch_name)"
-
-    local remote_name
-    remote_name="$(git_upstream_remote)"
-
     prepare_branch "${branch_name}" "${remote_name}"
 
     poetry_update_commit_changes "${branch_name}"
 
-    push_branch "${branch_name}"
+    push_branch "${branch_name}" "${remote_name}"
 
     local NEW_PR_URL
     gh_pr_create_and_auto_merge_when_checks_finish
@@ -208,9 +207,7 @@ poetry_update_commit_changes () {
 
 push_branch () {
   local branch_name="$1"
-
-  local remote_name
-  remote_name="$(git_upstream_remote)"
+  local remote_name="$2"
 
   print_prog "git push '${remote_name}'... "
 
@@ -239,20 +236,75 @@ push_branch () {
 # - We don't default to the sole remote if that's all there is.
 #   We're looking for a specific github.com/<org>/<proj> remote.
 git_upstream_remote () {
+  if [ -z "${UPDEPS_REPO_ORG_PROJ}" ]; then
+    local repo_url
 
-  if [ -z "${REPO_ORG_PROJ}" ]; then
-    >&2 echo "ERROR: Please set REPO_ORG_PROJ before calling update-poetry"
+    repo_url="$(print_upstream_remote_url)" || exit 1
 
-    exit 1
+    if [ -n "${repo_url}" ]; then
+      # Trim, e.g., https://github.com/doblabs/easy-as-pypi → doblabs/easy-as-pypi
+      # - Result is same as ${{ github.repository }}
+      UPDEPS_REPO_ORG_PROJ="$(
+        echo "${repo_url}" | sed 's#^.*/\([^/]*/[^/]*\)$#\1#'
+      )"
+
+      if [ -z "${UPDEPS_REPO_ORG_PROJ}" ]; then
+        >&2 echo "ERROR: Could not deduce project repo from URL: ${repo_url}"
+
+        exit 1
+      fi
+    else
+      >&2 echo "ERROR: Could not deduce remote URL from remotes or pyproject.toml"
+      >&2 echo "- Check pyproject.toml values for 'repository' or 'homepage'"
+      >&2 echo "  from [tool.poetry] or [tool.poetry.urls]"
+      >&2 echo "- Check \`git remote get-url origin\`"
+
+      exit 1
+    fi
   fi
 
   if ! git_upstream_remote_deduce; then
     # Note that we're ignoring the tracking branch. We want our GH
     # org/proj repo. Which we didn't find.
     >&2 echo "ERROR: Could not determine the upstream GitHub remote"
-    >&2 echo "- We checked REPO_ORG_PROJ (“${REPO_ORG_PROJ}”)"
+    >&2 echo "- We checked UPDEPS_REPO_ORG_PROJ (“${UPDEPS_REPO_ORG_PROJ}”)"
     >&2 echo "  against these remotes:"
     >&2 echo git remote -v
+
+    exit 1
+  fi
+}
+
+print_upstream_remote_url () {
+  if ${CI:-false}; then
+    git remote get-url "origin"
+  else
+    print_upstream_remote_url_from_pyproject_toml
+  fi
+}
+
+print_upstream_remote_url_from_pyproject_toml () {
+  if ! _updeps_insist_cmd 'tomlq'; then
+    >&2 echo "ERROR: Could not deduce upstream remote"
+    >&2 echo "- Please run from venv with \`tomlq\` installed"
+    >&2 echo "- Or set the 'UPDEPS_REPO_ORG_PROJ' environ"
+
+    exit 1
+  fi
+
+  # REFER: https://github.com/jqlang/jq/issues/354
+  local trim_null="select( . != null )"
+
+  if true \
+    && ! tomlq -r -e ".tool.poetry.repository      | ${trim_null}" "pyproject.toml" \
+    && ! tomlq -r -e ".tool.poetry.urls.repository | ${trim_null}" "pyproject.toml" \
+    && ! tomlq -r -e ".tool.poetry.homepage        | ${trim_null}" "pyproject.toml" \
+    && ! tomlq -r -e ".tool.poetry.urls.homepage   | ${trim_null}" "pyproject.toml" \
+  ; then
+    >&2 echo "ERROR: Could not deduce remote URL from pyproject.toml"
+    >&2 echo "- pyproject.toml is missing 'repository' or 'homepage'"
+    >&2 echo "  from [tool.poetry] or [tool.poetry.urls]"
+    >&2 echo "- You can also set 'UPDEPS_REPO_ORG_PROJ' environ directly"
 
     exit 1
   fi
@@ -261,8 +313,8 @@ git_upstream_remote () {
 git_upstream_remote_deduce () {
   git remote -v \
     | grep \
-        -e "[[:space:]]git@.*:${REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
-        -e "github.com/${REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
+        -e "[[:space:]]git@.*:${UPDEPS_REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
+        -e "github.com/${UPDEPS_REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
     | sed 's/^\([^[:space:]]\+\).*/\1/'
 }
 
@@ -328,7 +380,8 @@ gh_pr_create () {
   local pr_body="Cascading release"
   local new_pr_url
 
-  print_prog "gh pr create --title \"${pr_title}\" --body \"${pr_body}\"\n"
+  print_prog "gh pr create --title \"${pr_title}\" --body \"${pr_body}\"" \
+    "--label "${UPDEPS_LABEL_NAME_POETRY_LOCK}" ${pr_ci_labels}\n"
 
   # Create PR from user PAT so on auto-merge, it triggers workflow events.
 
@@ -433,5 +486,4 @@ fi
 
 unset -f main
 unset -f source_deps
-unset -f insist_cmd
 
