Feature: Option to po-update "our" deps or "all" deps
- Convert cascade-updates from bool to choices.

  - Previously was bool, true/false, during cascade:
    either update all deps (call raw `poetry update`),
    or skip.

  - Now it's a choice, can still 'skip' or choose 'all',
    but now a third option: 'ours', to update only "our"
    project dependencies.

    - Use case: Push bugfix (or any patch) without worrying
      about third-party dependency changes.

    - Use case: Update all deps to their latest versions (and
      dev is ready to debug any surprises).

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -24,6 +24,10 @@ UPDEPS_CASCADE_INHIBIT="${UPDEPS_CASCADE_INHIBIT:-false}"
 #   - Also what update-merged.yml uses when versioning current project.
 #   - Also what determines if we poetry-update pre-release assets, see below.
 UPDEPS_CASCADE_VERSIONING="${UPDEPS_CASCADE_VERSIONING:-alpha}"
+# - The cascade_updatedeps value to send on repository_dispatch.
+#   - Also what to po-update: "our" deps, or "all" (incl. 3rd-party), see below.
+#   - There's another option, "skip", but then this script is not called.
+UPDEPS_CASCADE_UPDATEDEPS="${UPDEPS_CASCADE_UPDATEDEPS:-all}"
 
 # ***
 
@@ -39,6 +43,7 @@ __UPDEPS__CPYST__="
   UPDEPS_FAKE_UPDATE=true \
   UPDEPS_CASCADE_INHIBIT=true \
   UPDEPS_CASCADE_VERSIONING=skip \
+  UPDEPS_CASCADE_UPDATEDEPS=skip \
     ./.github/bin/update-poetry
 "
 
@@ -62,6 +67,25 @@ UPDEPS_LABEL_NAME_INHIBIT_CASCADE="${UPDEPS_LABEL_NAME_INHIBIT_CASCADE:-\
 ci-inhibit-cascade}"
 UPDEPS_LABEL_DESC_INHIBIT_CASCADE="${UPDEPS_LABEL_DESC_INHIBIT_CASCADE:-\
 Tells CI not to cascade after versioning and release}"
+
+# ***
+
+# The cascade-updatedeps value-choices.
+
+UPDEPS_LABEL_NAME_UPDATE_OURS="${UPDEPS_LABEL_NAME_UPDATE_OURS:-\
+ci-update-ours}"
+UPDEPS_LABEL_DESC_UPDATE_OURS="${UPDEPS_LABEL_DESC_UPDATE_OURS:-\
+Tells CI to keep cascading update-\"ours\" after PR is approved}"
+
+UPDEPS_LABEL_NAME_UPDATE_ALL="${UPDEPS_LABEL_NAME_UPDATE_ALL:-\
+ci-update-all}"
+UPDEPS_LABEL_DESC_UPDATE_ALL="${UPDEPS_LABEL_DESC_UPDATE_ALL:-\
+Tells CI to keep cascading update-all after PR is approved}"
+
+UPDEPS_LABEL_NAME_UPDATE_SKIP="${UPDEPS_LABEL_NAME_UPDATE_SKIP:-\
+ci-update-skip}"
+UPDEPS_LABEL_DESC_UPDATE_SKIP="${UPDEPS_LABEL_DESC_UPDATE_SKIP:-\
+Tells CI to keep cascading update-skip after PR is approved}"
 
 # ***
 
@@ -208,16 +232,54 @@ update_and_commit_lock_normal () {
   return 1
 }
 
+# XPECT: Expects cwd is project root, and using EAPP Makefile.
+make_inspect_var () {
+  local var_name="$1"
+
+  # Prints Makefile variable. Same as, e.g.:
+  #
+  #   var_name=PYPROJECT_PRERELEASE_DIR
+  #   var_value="$(
+  #     make \
+  #       --eval="print-var: ; @echo \$(${var_name})" \
+  #       print-var
+  #   )"
+  #   printf "%s" "${var_value}"
+  #
+  # - But uses EAPP Makefile target that does the same.
+
+  make-inspect-var "${var_name}"
+}
+
 # ***
 
+# Call poetry-update, but let user choose the breadth/scope:
+# - If 'ours', only update "our" dependencies.
+#   - Use case: User wants to test their code changes, and they
+#               don't want to be surprised by a failure caused by
+#               changes to a third-party dependency.
+# - If 'all' (the recommended default), update all pyproject.toml
+#   dependencies.
+#   - Use case: User wants project to use latest deps,
+#               and, bonus, you make dependabot happy.
 poetry_update_lock_normal () {
   print_prog "poetry update... "
 
   if ! ${UPDEPS_FAKE_UPDATE:-false}; then
     # Meh: We could restrict to updating just our org's repos,
-    # e.g., `poetry update doblabs/<pkg> doblabs/<pkg> ...`,
-    # but no reason not to update everything.
-    poetry update -q --lock
+    if [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "ours" ]; then
+      # Restrict to updating just our org's repos (aka "our" deps).
+      poetry update -q --lock $(make_inspect_var "EDITABLE_PJS")
+    elif [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "all" ]; then
+      poetry update -q --lock
+    else
+      # Note that UPDEPS_CASCADE_UPDATEDEPS cannot be 'skip';
+      # caller precludes calling this script otherwise.
+      >&2 echo "GAFFE: Impossible path"
+
+      # D_b_C: This execution is kaput, by the laws of Design by Contract.
+      exit 1
+    fi
   else
     # UPDEPS_FAKE_UPDATE is a faker to make GH Actions CI testing quicker.
     echo "# This line generated by poetry-update-faker" >> poetry.lock
@@ -515,6 +577,7 @@ gh_label_create () {
 # Meh: This feels like TMBL — Too Much Business Logic — than maybe belongs here.
 print_pr_ci_labels () {
   print_pr_ci_labels_inhibit_cascade
+  print_pr_ci_labels_cascade_updatedeps
   print_pr_ci_labels_cascade_versioning
 }
 
@@ -525,6 +588,28 @@ print_pr_ci_labels_inhibit_cascade () {
       "${UPDEPS_LABEL_DESC_INHIBIT_CASCADE}"
 
     printf "%s" "--label ${UPDEPS_LABEL_NAME_INHIBIT_CASCADE} "
+  fi
+}
+
+print_pr_ci_labels_cascade_updatedeps () {
+  if [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "ours" ]; then
+    gh_label_create \
+      "${UPDEPS_LABEL_NAME_UPDATE_OURS}" \
+      "${UPDEPS_LABEL_DESC_UPDATE_OURS}"
+
+    printf "%s" "--label ${UPDEPS_LABEL_NAME_UPDATE_OURS} "
+  elif [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "all" ]; then
+    gh_label_create \
+      "${UPDEPS_LABEL_NAME_UPDATE_ALL}" \
+      "${UPDEPS_LABEL_DESC_UPDATE_ALL}"
+
+    printf "%s" "--label ${UPDEPS_LABEL_NAME_UPDATE_ALL} "
+  elif [ "${UPDEPS_CASCADE_UPDATEDEPS}" = "skip" ]; then
+    gh_label_create \
+      "${UPDEPS_LABEL_NAME_UPDATE_SKIP}" \
+      "${UPDEPS_LABEL_DESC_UPDATE_SKIP}"
+
+    printf "%s" "--label ${UPDEPS_LABEL_NAME_UPDATE_SKIP} "
   fi
 }
 
