Bugfix: update-poetry fails after `gh pr merge` if no checks enabled
- Bugfix: Also redirect `gh pr` output to stderr; workflow job
  expects stdout to contain PR number and breaks otherwise.

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -425,7 +425,10 @@ generate_branch_name () {
 prepare_branch () {
   local branch_name="$1"
 
-  if [ "$(git_branch_name)" = "${branch_name}" ]; then
+  local curr_branch
+  curr_branch="$(git_branch_name)"
+
+  if [ "${curr_branch}" = "${branch_name}" ]; then
     # Assumed previously called and all setup.
 
     return 0
@@ -433,7 +436,9 @@ prepare_branch () {
 
   # ***
 
-  local scoped_head="HEAD"
+  _ORIGINAL_BRANCH="${curr_branch}"
+
+  local scoped_head
   scoped_head="$(print_scoped_head ".")"
 
   print_prog "git checkout -b ${branch_name} ${scoped_head}\n"
@@ -452,7 +457,18 @@ prepare_branch () {
 resume_old_branch_and_cleanup () {
   local branch_name="$1"
 
-  git checkout -q -
+  # Note that `git checkout -` fails if `gh pr merge` deleted the PR branch.
+  #   $ git checkout -
+  #   error: pathspec '-' did not match any file(s) known to git
+  # So use branch name instead.
+
+  if [ -n "${_ORIGINAL_BRANCH}" ]; then
+    print_prog "git checkout -q ${_ORIGINAL_BRANCH}\n"
+
+    git checkout -q "${_ORIGINAL_BRANCH}"
+
+    _ORIGINAL_BRANCH=""
+  fi
 
   _CHANGED_BRANCH=""
 
@@ -464,10 +480,13 @@ resume_old_branch_and_cleanup () {
   # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
   if ! ${CI:-false}; then
     if ! ${UPDEPS_SKIP_PR:-false}; then
+      print_prog "git branch -q -D ${branch_name}\n"
       # Ignore stderr message that -q doesn't inhibit:
       #   warning: deleting branch 'foo' that has been merged to
       #            'refs/remotes/origin/foo', but not yet merged to HEAD.
-      git branch -q -D "${branch_name}" 2> /dev/null
+      # - Note that the earlier `gh pr merge` may have deleted the local
+      #   branch already, so avoid tripping errexit.
+      git branch -q -D "${branch_name}" 2> /dev/null || true
     else
       echo "You opted to not use a PR, so you'll need to merge changes yourself:"
       echo
@@ -701,7 +720,7 @@ gh_pr_create_and_auto_merge_when_checks_finish () {
     print_prog
   fi
 
-  print_prog "New PR\n  ${NEW_PR_URL}\n"
+  print_prog "New PR\n  ${NEW_PR_URL}\n\n"
 }
 
 gh_label_create_poetry_lock_label () {
@@ -831,8 +850,12 @@ gh_pr_set_auto_merge_delete_rebase () {
 
   print_prog "gh pr merge \"${pr_ref}\" --auto --delete-branch --rebase\n"
 
+  # SAVVY/2023-12-18: If there are no branch protection rules and
+  # mandatory checks, this'll actually merge immediately, and it'll
+  # delete the local branch. (And that's why `git checkout -` later
+  # fails.)
   GH_TOKEN=${USER_TOKEN} \
-  gh pr merge "${pr_ref}" --auto --delete-branch --rebase
+  gh pr merge "${pr_ref}" --auto --delete-branch --rebase 1>&2
 }
 
 # CXREF: https://github.com/doblabs/easy-as-pypi/settings/actions
@@ -856,7 +879,7 @@ gh_pr_approve () {
   # branch protection rule.
 
   GH_TOKEN=${GBOT_TOKEN} \
-  gh pr review "${pr_ref}" --approve --body "LGTM!" \
+  gh pr review "${pr_ref}" --approve --body "LGTM!" 1>&2 \
     || true
 }
 
@@ -1053,6 +1076,7 @@ exit_1 () { _NORMAL_EXIT=true; exit 1; }
 exit_0 () { _NORMAL_EXIT=true; exit 0; }
 
 _CHANGED_BRANCH=""
+_ORIGINAL_BRANCH=""
 
 exit_cleanup () {
   if [ -n "${_CHANGED_BRANCH}" ]; then
