Feature: Use pre-release sources (versions) for pre-release build
- Also wire pre-release poetry.lock update to bin/update-poetry,
  included whenever cascade-versioning is 'alpha' or 'least'.

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -29,6 +29,14 @@ UPDEPS_CASCADE_VERSIONING="${UPDEPS_CASCADE_VERSIONING:-alpha}"
 #   - There's another option, "skip", but then this script is not called.
 UPDEPS_CASCADE_UPDATEDEPS="${UPDEPS_CASCADE_UPDATEDEPS:-all}"
 
+# Just a convenience value for this module.
+UPDEPS_INCLUDE_PRERELEASE="$(
+  [ "${UPDEPS_CASCADE_VERSIONING}" != "least" ] \
+  && [ "${UPDEPS_CASCADE_VERSIONING}" != "alpha" ] \
+  && echo false \
+  || echo true
+)"
+
 # ***
 
 # Optional: Set faker true to skip poetry-update (useful for developing).
@@ -126,6 +134,8 @@ UPDEPS_LABELS_COLOR="${UPDEPS_LABELS_COLOR:-74e34f}"
 # Optional: Customizable Git commit messages.
 UPDEPS_COMMIT_MESSAGE_NORMAL="${UPDEPS_COMMIT_MESSAGE_NORMAL:-\
 Build: Deps: Update poetry.lock [bin/update-poetry]}"
+UPDEPS_COMMIT_MESSAGE_PRERELEASE="${UPDEPS_COMMIT_MESSAGE_PRERELEASE:-\
+Build: Deps: Update pre-release assets [bin/update-poetry]}"
 
 # Optional: Customizable GitHub PR title and body.
 UPDEPS_PR_TITLE="${UPDEPS_PR_TITLE:-Build: Update deps}"
@@ -195,6 +205,10 @@ update_poetry_update () {
     has_changes=true
   fi
 
+  if update_and_commit_lock_prerelease "${branch_name}"; then
+    has_changes=true
+  fi
+
   if ${has_changes}; then
     push_branch "${branch_name}" "${remote_name}"
 
@@ -224,6 +238,37 @@ update_and_commit_lock_normal () {
     prepare_branch "${branch_name}"
 
     poetry_update_commit_changes_normal
+
+    return 0
+  fi
+
+  return 1
+}
+
+update_and_commit_lock_prerelease () {
+  local branch_name="$1"
+
+  if ! ${UPDEPS_INCLUDE_PRERELEASE}; then
+    return 1
+  fi
+
+  # ***
+
+  # Fetch Makefile's PYPROJECT_PRERELEASE_DIR value.
+  local pyproject_dir
+  pyproject_dir="$(make_inspect_var "PYPROJECT_PRERELEASE_DIR")"
+
+  poetry_update_lock_prerelease
+
+  assert_git_status_0_1_or_2_changes
+
+  assert_git_status_only_prerelease_pyproject_and_or_lock_changed_if_any \
+    "${pyproject_dir}"
+
+  if test -n "$(git status --porcelain=v1)"; then
+    prepare_branch "${branch_name}"
+
+    poetry_update_commit_changes_prerelease "${pyproject_dir}"
 
     return 0
   fi
@@ -278,6 +323,21 @@ poetry_update_lock_normal () {
   fi
 
   print_prog "✓\n"
+}
+
+poetry_update_lock_prerelease () {
+  print_prog "poetry update...  # pre-release"
+
+  # Create <dir>/pyproject.toml and <dir>/poetry.lock, each copied
+  # from project root and then edited or updated.
+  # - The pre-release toml and lock are identical to the normal
+  #   project files, expect "our" deps are updated to whatever's
+  #   on test.PyPI — and it's expected that anyone who installs
+  #   the pre-release package will install using something like:
+  #     pip --index-url https://test.pypi.org/simple \
+  #       --extra-index-url=https://pypi.org/simple/ \
+  #       <pkg>
+  make prepare-poetry-prerelease
 }
 
 # ***
@@ -357,6 +417,14 @@ resume_old_branch_and_cleanup () {
 poetry_update_commit_changes () {
   local commit_message="$1"
 
+  if ${UPDEPS_INCLUDE_PRERELEASE} \
+    && has_changes_pyproject_toml \
+  ; then
+    print_prog "git add pyproject.toml\n"
+
+    git add pyproject.toml
+  fi
+
   if has_changes_poetry_lock; then
     print_prog "git add poetry.lock\n"
 
@@ -372,6 +440,16 @@ poetry_update_commit_changes () {
 
 poetry_update_commit_changes_normal () {
   poetry_update_commit_changes "${UPDEPS_COMMIT_MESSAGE_NORMAL}"
+}
+
+poetry_update_commit_changes_prerelease () {
+  local pyproject_dir="$1"
+
+  (
+    cd "${pyproject_dir}"
+
+    poetry_update_commit_changes "${UPDEPS_COMMIT_MESSAGE_PRERELEASE}"
+  )
 }
 
 # ***
@@ -742,6 +820,10 @@ assert_git_status_0_or_1_changes () {
   assert_git_status_changes_le_max 1
 }
 
+assert_git_status_0_1_or_2_changes () {
+  assert_git_status_changes_le_max 2
+}
+
 assert_git_status_changes_le_max () {
   local max="$1"
 
@@ -772,10 +854,43 @@ assert_git_status_only_poetry_lock_changed_if_any () {
   exit 1
 }
 
+assert_git_status_only_prerelease_pyproject_and_or_lock_changed_if_any () {
+  local pyproject_dir="$1"
+
+  local git_status
+  git_status="$(cd "${pyproject_dir}" && git status --porcelain=v1)"
+
+  test -z "${git_status}" \
+    && return 0 || true
+
+  local expect_if_both_changed="\
+ M poetry.lock
+ M pyproject.toml"
+
+  if [ "${git_status}" = " M poetry.lock" ] \
+    || [ "${git_status}" = " M pyproject.toml" ] \
+    || [ "${git_status}" = "${expect_if_both_changed}" ] \
+  ; then
+
+    return 0
+  fi
+
+  # Should be unreachable path.
+  >&2 echo "ERROR: Unexpected: Something other than pyproject.toml or poetry.lock"
+  >&2 echo "                   has changes after poetry-update?!"
+  >&2 echo "${git_status}"
+
+  exit 1
+}
+
 # ***
 
 has_changes_poetry_lock () {
   has_unstaged_changes "poetry.lock"
+}
+
+has_changes_pyproject_toml () {
+  has_unstaged_changes "pyproject.toml"
 }
 
 has_unstaged_changes () {
diff --git a/.github/workflows/release-github.yml b/.github/workflows/release-github.yml
--- a/.github/workflows/release-github.yml
+++ b/.github/workflows/release-github.yml
@@ -126,9 +126,51 @@ jobs:
           python-version: ${{ env.PYTHON_VERSION }}
           cache: 'poetry'
 
+      # NOICE: DRY: Use `make --eval` to add temp. make target that prints
+      # the pre-release pyproject.toml directory (avoids USYNC/hardcoding).
+      - name: Determine pyproject.toml to use (normal or alpha)
+        run: |
+          pyproject_dir="."
+          if [ "${PRERELEASE}" = "--prerelease" ]; then
+            pyproject_dir="$(
+              make \
+                --eval='print-var: ; @echo $(PYPROJECT_PRERELEASE_DIR)' \
+                print-var
+            )"
+          fi
+          echo "PYPROJECT_DIR=${pyproject_dir}" >> "${GITHUB_ENV}"
+
+      - name: Verify Poetry assets — pyproject.toml and poetry.lock
+        run: |
+          assets_exist () {
+            local pyproject_dir="${1:-.}"
+
+            [ -f "${pyproject_dir}/pyproject.toml" ] \
+            && [ -f "${pyproject_dir}/poetry.lock" ]
+          }
+
+          if [ "${PRERELEASE}" = "--prerelease" ]; then
+            if ! assets_exist "${PYPROJECT_DIR}"; then
+              >&2 echo "ERROR: Where are the ${PYPROJECT_DIR} Poetry assets?"
+              >&2 echo "- Missing pyproject.toml and/or poetry.lock"
+              >&2 echo "- HINT: Run the update-deps.yml workflow"
+              >&2 echo "  - OR: Run \`make prepare-poetry-prerelease\`"
+              >&2 echo "        and then commit the two files to the repo"
+
+              exit 1
+            fi
+          elif ! assets_exist; then
+            >&2 echo "ERROR: Missing pyproject.toml and/or poetry.lock"
+            >&2 echo "- HINT: Run the update-deps.yml workflow"
+            >&2 echo "  - OR: Run \`make install\`"
+            >&2 echo "        and then commit the lock file to the repo"
+
+            exit 1
+          fi
+
       - name: Poetry build
         run: |
-          poetry build
+          poetry -C "${PYPROJECT_DIR}" build
 
       - name: Probe filename
         run: |
