Bugfix: Set Git user name and email prior to wrangling CI tags

diff --git a/.github/workflows/ci-tags-wrangle.yml b/.github/workflows/ci-tags-wrangle.yml
--- a/.github/workflows/ci-tags-wrangle.yml
+++ b/.github/workflows/ci-tags-wrangle.yml
@@ -112,6 +112,30 @@ jobs:
 
       # ***
 
+      # NODRY: See similar steps: ci-tags-wrangle.yml, update-merged.yml
+      - name: Prepare committer
+        run: |
+          assert_git_email_known_ci () {
+            test -n "${UPDEPS_USER_EMAIL}" \
+              && return 0 || true
+
+            >&2 echo "ERROR: Please set UPDEPS_USER_EMAIL " \
+              "organization or project variable"
+
+            exit 1
+          }
+          assert_git_email_known_ci
+
+          git config user.email "${UPDEPS_USER_EMAIL}"
+          git config user.name \
+            "${UPDEPS_USER_NAME_CI_TAGS:-${UPDEPS_USER_NAME:-release-bot}}"
+        env:
+          UPDEPS_USER_EMAIL: ${{ vars.UPDEPS_USER_EMAIL }}
+          UPDEPS_USER_NAME: ${{ vars.UPDEPS_USER_NAME }}
+          UPDEPS_USER_NAME_CI_TAGS: ${{ vars.UPDEPS_USER_NAME_CI_TAGS }}
+
+      # ***
+
       - name: Wrangle CI tags
         id: wrangle-ci-tags
         run: |
