Update: CI: Check alpha branch for latest release version
- On user-activated (workflow_dispatch) release-pypi,
  fallback optional pre-release branch if version tag
  not found on default branch HEAD.

diff --git a/.github/workflows/release-pypi.yml b/.github/workflows/release-pypi.yml
--- a/.github/workflows/release-pypi.yml
+++ b/.github/workflows/release-pypi.yml
@@ -111,17 +111,52 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.repository.default_branch }}
-          # Fetch all history, so rev-parse HEAD is real HEAD.
+          # Grab everything, because we might need to switch branches
+          # in the next step.
           fetch-depth: 0
         if: github.event_name == 'workflow_dispatch'
 
+      # Check the default branch HEAD for a version tag.
+      # - If it's not found, try the pre-release branch.
+      # - T_M_I: Note there are 2 branches that might be version-tagged:
+      #     the main, default branch; and
+      #     the 'liminal' (pre-release) branch.
+      #   - Within the main branch, if any commit has a pre-release version,
+      #     that commit *also* has a normal version.
+      #   - In the other, 'liminal', branch, it's the other way around: any
+      #     commit might only have a pre-release version, or nothing, but any
+      #     commit in the 'liminal' branch with a normal version also has a
+      #     pre-release version.
       - name: Probe version tag (is workflow_dispatch)
         if: github.event_name == 'workflow_dispatch'
+        env:
+          PRERELEASE_BRANCH: ${{ vars.PRERELEASE_BRANCH }}
         run: |
-          version_tags="$(
+          print_version_tags () {
             git tag --list --points-at HEAD \
-              | grep -E -e "${VERSPARTS}" \
-          )"
+              | grep -E -e "${VERSPARTS}"
+          }
+
+          branch_name="$(git rev-parse --abbrev-ref=loose HEAD)"
+
+          version_tags="$(print_version_tags)"
+
+          if [ -z "${version_tags}" ] && [ -n "${PRERELEASE_BRANCH}" ]; then
+            # Try the pre-release branch.
+            git checkout ${PRERELEASE_BRANCH}
+
+            branch_name="${PRERELEASE_BRANCH}"
+
+            version_tags="$(print_version_tags)"
+          fi
+
+          if [ -z "${version_tags}" ]; then
+            >&2 echo "ERROR: Nothing to do: HEAD(s) not versioned"
+
+            exit 1
+          fi
+
+          echo "Version tag(s) on “${branch_name}”: ${version_tags}"
 
           # If multiple versions tagged, choose the largest.
           # - Note this is quite unnecessary, as this use case (a user
