Build: CI: Improve: Required git-commit user from envs (org vars)
- Replace (my) hardcoded commit email/name with environs the
  bin/update-poetry script now requires.

  - So no longer falls back on `git config user.email`.

- Behavior is opposite when run interactively: script expects
  `git config user.email`, and it ignores environ value.

- Easiest path to compliance is to add GitHub organization variables.

diff --git a/.github/workflows/update-merged.yml b/.github/workflows/update-merged.yml
--- a/.github/workflows/update-merged.yml
+++ b/.github/workflows/update-merged.yml
@@ -194,9 +194,21 @@ jobs:
 
       - name: Prepare committer
         run: |
+          assert_git_email_known_ci () {
+            test -n "${UPDEPS_USER_EMAIL}" \
+              && return 0 || true
+
+            >&2 echo "ERROR: Please set UPDEPS_USER_EMAIL " \
+              "organization or project variable"
+
+            exit 1
+          }
+          assert_git_email_known_ci
+
           cd ./versionee/
-          git config user.email "${UPDEPS_USER_EMAIL:-landonb@users.noreply.github.com}"
-          git config user.name "${UPDEPS_USER_NAME:-release-bot}"
+          git config user.email "${UPDEPS_USER_EMAIL}"
+          git config user.name \
+            "${UPDEPS_USER_NAME_VERSION:-${UPDEPS_USER_NAME:-release-bot}}"
 
       - name: Bump it...
         run: |
